name: the_process
description: A tool to automate "the process", a system for organising collaboration.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # astro
  auth_for_perception: ^0.0.0-a1
  core_of_perception: ^0.0.0-a1
  error_handling_for_perception: ^0.0.0-a1
  inspector_for_perception: ^0.0.0-a1
  locator_for_perception: ^0.0.0-a1
  navigation_for_perception: ^0.0.0-a1
  types_for_perception: ^0.0.0-a1

  # firestore
  firestore_service_flutterfire: ^0.0.0-a1
  firestore_service_interface: ^0.0.0-a1

  # types
  json_utils: ^0.0.0-a1
  types_for_auth: ^0.0.0-a1

  # utils 
  uuid: ^3.0.7
  http: ^1.0.0
  collection: ^1.17.1
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  enspyr_lints: ^0.0.0-a1
  build_runner: ^2.4.5
  builders_for_perception: ^0.0.0-a1
  test_utils_for_perception: ^0.0.0-a1

flutter:
  uses-material-design: true # we use material icons for dropdowns etc.
