name: the_process
description: A tool to automate "the process", a system for organising collaboration.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # astro
  astro_core: ^0.0.0-a1
  astro_types: ^0.0.0-a1
  astro_locator: ^0.0.0-a1
  astro_inspector_screen: ^0.0.0-a1
  astro_auth: ^0.0.0-a1
  astro_error_handling: ^0.0.0-a1
  astro_navigation: ^0.0.0-a1

  # firestore
  firestore_service_flutterfire: ^0.0.0-a1
  firestore_service_interface: ^0.0.0-a1

  # utils 
  uuid: ^3.0.7
  http: ^1.0.0
  collection: ^1.17.1
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.5
  astro_generators: ^0.0.0-a1
  astro_test_utils: ^0.0.0-a1
  enspyr_lints: ^0.0.0-a1

flutter:
  uses-material-design: true # we use material icons for dropdowns etc.
