name: the_process
description: A tool to automate "the process", a system for organising collaboration.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # astro
  percepts:
    git: https://github.com/enspyrco/percepts
  abstractions:
    git: https://github.com/enspyrco/abstractions
  locator_for_perception:
    git: https://github.com/enspyrco/locator_for_perception
  introspection:
    git: https://github.com/enspyrco/introspection
  error_correction_in_perception:
    git: https://github.com/enspyrco/error_correction_in_perception
  framing_in_perception:
    git: https://github.com/enspyrco/framing_in_perception
  
  flutterfire_firebase_auth_for_perception:
    git: https://github.com/enspyrco/flutterfire_firebase_auth_for_perception

  # firestore
  firestore_service_interface:
    git: https://github.com/enspyrco/firestore_service_interface
  flutterfire_firestore_service:
    git: https://github.com/enspyrco/flutterfire_firestore_service

  # types
  types_for_auth:
    git: https://github.com/enspyrco/types_for_auth
  json_utils:
    git: https://github.com/enspyrco/json_utils

  # utils 
  uuid: ^3.0.7
  http: ^1.0.0
  collection: ^1.17.2
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
  test_utils_for_perception:
    git: https://github.com/enspyrco/test_utils_for_perception

flutter:
  uses-material-design: true # we use material icons for dropdowns etc.
