name: the_process
description: A tool to automate "the process", a system for organising collaboration.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # astro
  core_of_perception:
    git: https://github.com/enspyrco/core_of_perception
  types_for_perception:
    git: https://github.com/enspyrco/types_for_perception
  locator_for_perception:
    git: https://github.com/enspyrco/locator_for_perception
  inspector_for_perception:
    git: https://github.com/enspyrco/inspector_for_perception
  auth_for_perception:
    git: https://github.com/enspyrco/auth_for_perception
  error_handling_for_perception:
    git: https://github.com/enspyrco/error_handling_for_perception
  navigation_for_perception:
    git: https://github.com/enspyrco/navigation_for_perception
  
  # auth
  firebase_auth_service_interface:
    git: https://github.com/enspyrco/firebase_auth_service_interface
  firebase_auth_service_flutterfire:
    git: https://github.com/enspyrco/firebase_auth_service_flutterfire

  # firestore
  firestore_service_interface:
    git: https://github.com/enspyrco/firestore_service_interface
  firestore_service_flutterfire:
    git: https://github.com/enspyrco/firestore_service_flutterfire

  # types
  types_for_auth:
    git: https://github.com/enspyrco/types_for_auth
  json_utils:
    git: https://github.com/enspyrco/json_utils

  # utils 
  uuid: ^3.0.7
  http: ^1.0.0
  collection: ^1.18.0
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
  test_utils_for_perception:
    git: https://github.com/enspyrco/test_utils_for_perception

flutter:
  uses-material-design: true # we use material icons for dropdowns etc.
